import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { ClientLayout } from './ClientLayout'

const roboto = Roboto({
    weight: ['400', '500', '700'],
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-roboto',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="ko">
            <body className={`${roboto.variable} font-roboto antialiased`}>
                <ClientLayout>{children}</ClientLayout>
            </body>
        </html>
    )
}
